apiVersion: apps/v1
kind: Deployment
metadata:
  name: app_deploy
  namespace: safernandez666
  labels:
    app: app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: safernandez666/app:${{ github.sha }}
        ports:
        - containerPort: 80
        imagePullPolicy: "Always"
---

apiVersion: v1
kind: Service
metadata:  
  name: app_deploy
  namespace: safernandez666
spec:
  selector:
    app: app
  type: LoadBalancer
  ports:  
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
