---
name: build latest

on:
  push:
    branches:
    - 'main'

jobs:
  build-and-push-latest:
    runs-on: ubuntu-latest
    steps:
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      context: ./
      file: app/Dockerfile
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: safernandez666/app:latest