name: Publish To Docker & Okteto

on:
  push:
    branches:
      - 'main'

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: safernandez666/app:latest,safernandez666/app:${{ github.sha }}  
      - 
        name: checkout
        uses: actions/checkout@master
        
      - uses: okteto/login@master
        with:
          token: ${{ secrets.KUBE_CONFIG_DATA }}
      
      - name: "Activate personal namespace"
        uses: okteto/namespace@master
        with:
          name: safernandez666

      - name: "Create deployment"
        uses: okteto/apply@master
        with:
          manifest: deployments/app.yaml