name: CI

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
    steps:
      - 
        name: Login to DockerHub Registry
        uses: actions/checkout@v1
        run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          file: app/Dockerfile
          push: true
          tags: safernandez666/app:latest