name: Publish To Docker & Okteto

on:
  push:
    branches:
      - 'main'

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: safernandez666/app:latest,safernandez666/app:${{ github.sha }}  
      - 
        uses: actions/checkout@v2

      ### Deploy en Cluster de Okteto
      - uses: okteto/login@master
        with:
          token: ${{ secrets.OKTETO_TOKEN }}
      
      - name: "Activate personal namespace"
        uses: okteto/namespace@master
        with:
          name: safernandez666

      - name: "Create deployment"
        uses: okteto/apply@master
        with:
          manifest: deployments/app.yaml
      - 
        name: Deploy to cluster
        uses: myrotvorets/kubectl-action@2.0.0
        with:
          config: ${{ secrets.KUBE_CONFIG_DATA }}
          version: latest
          args: set image --record deployment/app-deploy app-deploy=safernandez666/app:${{ github.sha }}
      - 
        name: Verify deployment
        uses: myrotvorets/kubectl-action@2.0.0
        with:
          config: ${{ secrets.KUBE_CONFIG_DATA }}
          version: latest
          args: '"rollout status deployment/app-deploy"'