name: Publish To Docker & Okteto

on:
  push:
    branches:
      - 'main'

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: safernandez666/app:latest,safernandez666/app:${{ github.sha }}
          cache-from: type=registry,ref=safernandez666/app:latest
          cache-to: type=inline
  CD:
    runs-on: ubuntu-latest
    if: github.event_name == 'CI' && github.ref == 'refs/heads/main'
    steps:
      - name: Deploy to Cluster
        uses: steebchen/kubectl@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        with:
          args: set image --record deployment/app_deploy app=safernandez666/app:${{ github.sha }} 
      
      - name: Verify Deployment
        uses: steebchen/kubectl@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
          KUBECTL_VERSION: "1.15"
        with:
          args: '"rollout status deployment/app_deploy"'